#/bin/bash

top_dir=$PWD

find src -maxdepth 1 -mindepth 1 -type d | while read dir
do 
	cd $dir
	sources=$(ls *.[ch] | tr '\n' ' ')
	{
		echo "# generated by $0"
		echo "libipv6_care_$(basename $dir)_la_SOURCES = $sources" 
	} > Makefile.src_info
	cd $top_dir
done 

